services:
  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - ./init-db:/docker-entrypoint-initdb.d/
  dynamic:
    build: ./docker
    ports:
      - "8080:8080"
    volumes: 
      - ./code/dynamic:/var/www/html
      - ./ports.conf:/etc/apache2/ports.conf
  static:
    image: nginx
    volumes:
      - ./code/static:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"

